=== ludovic-source/formationBNPPEpitaGit/JavaXML/xml/arbre.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT racine (tronc)+>
        <!ELEMENT tronc (branche)+>
        <!ATTLIST tronc nom CDATA #REQUIRED>
        <!ELEMENT branche (fruit+,feuille+)>
        <!ATTLIST branche nom CDATA #REQUIRED>
        <!ELEMENT fruit (nom,couleur)+>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT couleur (#PCDATA)>
        <!ELEMENT feuille (#PCDATA)>

=== ludovic-source/formationBNPPEpitaGit/JavaXML/xml/arbre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE racine SYSTEM "arbre.dtd">

<racine>
    <!-- xs:noNamespaceSchemaLocation="arbre.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    > -->
    <tronc nom="tronc secondaire">
        <branche nom="branche1">
            <fruit>
                <nom>Pommes</nom>
                <couleur>Jaune</couleur>
            </fruit>
            <fruit>
                <nom>Cerise</nom>
                <couleur>Rouge</couleur>
            </fruit>
            <feuille>Feuille normale</feuille>
        </branche>
        <branche nom="branche2">
            <fruit>
                <nom>Pommes</nom>
                <couleur>Jaune</couleur>
            </fruit>
            <fruit>
                <nom>Cerise</nom>
                <couleur>Rouge</couleur>
            </fruit>
            <feuille>Feuille normale</feuille>
            <feuille>Deuxi√®me feuille</feuille>
        </branche>
    </tronc>
</racine>
